# Generated by Django 5.2.12 on 2026-03-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_todo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'managed': False, 'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'managed': False},
        ),
    ]
