# Generated by Django 5.2.12 on 2026-03-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user_id',
            new_name='user',
        ),
    ]
