# Generated by Django 5.2.12 on 2026-03-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_user_id_todolist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='list_id',
            new_name='list',
        ),
    ]
